name: Minimal Docker to ECR

on:
  push:
    branches:
      - master

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login à ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Build & Push vers ECR
      - name: Build and Push Docker image
        run: |
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          IMAGE_REPO_NAME=test-aws
          IMAGE_TAG=latest

          ECR_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}"

          echo "➡️ Build image $ECR_URI"
          docker build -t $ECR_URI .

          echo "➡️ Push image to ECR"
          docker push $ECR_URI
